{
    "name": "Telegram AI Hub",
    "summary": "Secure Telegram AI assistant for Odoo business operations",
    "version": "19.0.2.0.0",
    "category": "Productivity",
    "license": "OPL-1",
    "price": 150.0,
    "currency": "USD",
    "author": "ResilientByte Maroc",
    "website": "https://kone-adama.com",
    "support": "contact@kone-adama.com",
    "depends": [
        "base",
        "mail",
        "web",
        "crm",
        "sale_management",
        "account",
        "stock",
        "calendar",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/channel_data.xml",
        "data/allowed_actions.xml",
        "views/messaging_views.xml",
        "views/telegram_views.xml",
        "views/ai_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "telegram_ai_hub/static/src/dashboard/dashboard.js",
            "telegram_ai_hub/static/src/dashboard/dashboard.xml",
            "telegram_ai_hub/static/src/dashboard/dashboard.scss",
        ],
    },
    "images": ["static/description/cover_screenshot.gif"],
    "application": True,
    "installable": True,
    "auto_install": False,
}
